{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'streamlit'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mnumpy\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mnp\u001b[39;00m\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mstreamlit\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mas\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mst\u001b[39;00m\n\u001b[1;32m      3\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;21;01mtyping\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mimport\u001b[39;00m Tuple, Optional\n\u001b[1;32m      5\u001b[0m \u001b[38;5;66;03m# --- CONFIGURATION CLASS (Same as before) ---\u001b[39;00m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'streamlit'"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import streamlit as st\n",
    "from typing import Tuple, Optional\n",
    "\n",
    "# --- CONFIGURATION CLASS (Same as before) ---\n",
    "class DiveConfig:\n",
    "    def __init__(self):\n",
    "        self.HALF_TIMES_N2 = np.array([4.0, 8.0, 12.5, 18.5, 27.0, 38.3, 54.3, 77.0,\n",
    "                                       109.0, 146.0, 187.0, 239.0, 305.0, 390.0, 498.0, 635.0])\n",
    "        self.HALF_TIMES_HE = np.array([1.51, 3.02, 4.72, 6.99, 10.21, 14.48, 20.53, 29.11,\n",
    "                                       41.20, 55.19, 70.69, 90.34, 115.29, 147.42, 188.24, 240.03])\n",
    "        self.CONSERVATISM_LEVEL = 2\n",
    "        self.ASCENT_RATE = 9.0\n",
    "        self.SURFACE_PRESSURE = 1.013\n",
    "        self.BAR_PER_METER = 0.098\n",
    "        self.PRESSURE_OTHER_GASES = 0.102\n",
    "        self.k_n2 = np.log(2) / self.HALF_TIMES_N2\n",
    "        self.k_he = np.log(2) / self.HALF_TIMES_HE\n",
    "\n",
    "    def get_vpm_gradients(self) -> np.ndarray:\n",
    "        effective_ht = (self.HALF_TIMES_N2 + self.HALF_TIMES_HE) / 2\n",
    "        g_base = 0.35 + (0.65 / np.sqrt(effective_ht / 10.0))\n",
    "        conservatism_factor = 1.0 - (0.05 * self.CONSERVATISM_LEVEL)\n",
    "        return g_base * conservatism_factor\n",
    "\n",
    "config = DiveConfig()\n",
    "\n",
    "# --- PHYSICS FUNCTIONS (Same as before) ---\n",
    "def calculate_ambient_pressure(depth):\n",
    "    return config.SURFACE_PRESSURE + depth * config.BAR_PER_METER\n",
    "\n",
    "def load_tissues(depth, time, fo2, fn2, fhe, initial_n2=None, initial_he=None):\n",
    "    ambient = calculate_ambient_pressure(depth)\n",
    "    dry_pressure = ambient - config.PRESSURE_OTHER_GASES\n",
    "    p_insp_n2, p_insp_he = fn2 * dry_pressure, fhe * dry_pressure\n",
    "    \n",
    "    if initial_n2 is None:\n",
    "        initial_n2 = np.full(16, 0.79 * config.SURFACE_PRESSURE)\n",
    "    if initial_he is None:\n",
    "        initial_he = np.zeros(16)\n",
    "        \n",
    "    n2_load = p_insp_n2 + (initial_n2 - p_insp_n2) * np.exp(-config.k_n2 * time)\n",
    "    he_load = p_insp_he + (initial_he - p_insp_he) * np.exp(-config.k_he * time)\n",
    "    return n2_load, he_load\n",
    "\n",
    "def calculate_vpm_ceiling_detailed(n2_loading, he_loading, depth):\n",
    "    ambient = calculate_ambient_pressure(depth)\n",
    "    total_loading = n2_loading + he_loading\n",
    "    g_crits = config.get_vpm_gradients()\n",
    "    req_amb = total_loading - g_crits\n",
    "    depths = np.maximum(0.0, (req_amb - config.SURFACE_PRESSURE) / config.BAR_PER_METER)\n",
    "    max_ceiling = np.max(depths)\n",
    "    leader = int(np.argmax(depths)) if max_ceiling > 0.0 else -1\n",
    "    return max_ceiling, leader\n",
    "\n",
    "# --- WEB INTERFACE (STREAMLIT) ---\n",
    "st.set_page_config(page_title=\"VPM-B Dive Planner\", page_icon=\"🤿\")\n",
    "\n",
    "st.title(\"🤿 VPM-B offgassing Calculator\")\n",
    "st.markdown(\"Interactive teaching tool for **VPM-B Algorithm** physics.\")\n",
    "\n",
    "# Sidebar inputs\n",
    "st.sidebar.header(\"Dive Profile\")\n",
    "fo2 = st.sidebar.slider(\"Oxygen (%)\", 0, 100, 25) / 100.0\n",
    "fhe = st.sidebar.slider(\"Helium (%)\", 0, 100, 25) / 100.0\n",
    "fn2 = 1.0 - fo2 - fhe\n",
    "\n",
    "st.sidebar.markdown(f\"**Nitrogen:** {fn2*100:.1f}%\")\n",
    "if fn2 < 0:\n",
    "    st.error(\"Invalid Gas Mix: Fractions exceed 100%\")\n",
    "    st.stop()\n",
    "\n",
    "max_depth = st.sidebar.number_input(\"Max Depth (m)\", min_value=0.0, value=30.0)\n",
    "bottom_time = st.sidebar.number_input(\"Bottom Time (min)\", min_value=0.0, value=45.0)\n",
    "\n",
    "if st.sidebar.button(\"Calculate Decompression\"):\n",
    "    # Simulation Logic (Simplified for web display)\n",
    "    n2_load, he_load = load_tissues(max_depth, bottom_time, fo2, fn2, fhe)\n",
    "    ceiling, leader_idx = calculate_vpm_ceiling_detailed(n2_load, he_load, max_depth) # Check at bottom first\n",
    "    \n",
    "    # Simple ascent simulation for display\n",
    "    current_depth = max_depth\n",
    "    max_ceiling_found = 0.0\n",
    "    leading_tissue_final = -1\n",
    "    \n",
    "    # Quick simulation loop\n",
    "    for _ in range(int(max_depth / 0.5)): # Step up\n",
    "        c, l = calculate_vpm_ceiling_detailed(n2_load, he_load, current_depth)\n",
    "        if c > max_ceiling_found:\n",
    "            max_ceiling_found = c\n",
    "            leading_tissue_final = l\n",
    "        \n",
    "        # Update tissues for small step\n",
    "        n2_load, he_load = load_tissues(current_depth - 0.5, 0.05, fo2, fn2, fhe, initial_n2=n2_load, initial_he=he_load)\n",
    "        current_depth -= 0.5\n",
    "        if current_depth < 0: break\n",
    "\n",
    "    # Display Results\n",
    "    st.divider()\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "    \n",
    "    with col1:\n",
    "        st.metric(\"Ceiling Depth\", f\"{max_ceiling_found:.1f} m\")\n",
    "    with col2:\n",
    "        tissue_name = f\"T{leader_idx+1}\" if leader_idx != -1 else \"None\"\n",
    "        st.metric(\"Leading Tissue\", tissue_name)\n",
    "    with col3:\n",
    "        status = \"⚠️ DECO REQUIRED\" if max_ceiling_found > 0 else \"✅ NO DECO\"\n",
    "        st.metric(\"Status\", status)\n",
    "\n",
    "    if max_ceiling_found > 0:\n",
    "        st.warning(f\"**Stop Required:** Do not ascend shallower than **{max_ceiling_found:.1f} meters**.\")\n",
    "        st.info(f\"This stop is forced by **Tissue {leader_idx+1}** (Half-time: {config.HALF_TIMES_N2[leader_idx]} min N2).\")\n",
    "        \n",
    "        # Visualizer\n",
    "        st.subheader(\"Tissue Loading vs. Critical Gradient\")\n",
    "        total_load = n2_load + he_load\n",
    "        g_crits = config.get_vpm_gradients()\n",
    "        ambient_surface = config.SURFACE_PRESSURE\n",
    "        \n",
    "        chart_data = {\n",
    "            'Tissue': [f\"T{i+1}\" for i in range(16)],\n",
    "            'Inert Gas Pressure (bar)': total_load,\n",
    "            'Critical Limit (bar)': ambient_surface + g_crits\n",
    "        }\n",
    "        st.bar_chart(chart_data, x='Tissue', y=['Inert Gas Pressure (bar)', 'Critical Limit (bar)'])\n",
    "    else:\n",
    "        st.success(\"You can ascend directly to the surface (safety stop still recommended).\")\n",
    "\n",
    "# Footer\n",
    "st.markdown(\"---\")\n",
    "st.caption(\"Generated for Educational Purposes | VPM-B Algorithm Implementation\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.1+"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
